[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "example-pkg"
version = "0.1.0"
description = "Example package"
authors = [{name="You", email="you@example.com"}]
readme = "README.md"
requires-python = ">=3.10"
